### ISSUE TITLE
Customer dashboard « forgotten password » feature do not work.

### ISSUE THREAD

**Issue by MachinisteWeb** [snipcart/snipcart.github.io#1]
## Customer dashboard « forgotten password » issue

On our tested page: https://blog.lesieur.name/espace-membres/

When you click on « Customer dashboard », you click on « J'ai oublié mon mot de passe », you field input with « bruno.lesieur@gmail.com » or « b.lesieur@orchard-id.com », you click on « OK » button : **nothing will be produce, and no email will be send. In the console.log you will see** :

![snipcart-forgotten-password](https://user-images.githubusercontent.com/3882169/28963721-71200142-790a-11e7-8455-f8dc38515f4f.jpg)

In this example I clicked twice time on « OK » button.

## Try to reset the Template email to first configuration

We have not change the Template Email for « FORGOT PASSWORD » but we have tested to reset it to see if that solve the issue. In back-office, page `https://app.snipcart.com/dashboard/email-templates`, part « FORGOT PASSWORD » we have clicked on « EDIT » button, then on next page, we have clicked on « RESTORE DEFAULT » button and then, we have clicked on « SAVE & EXIT » button.

After new test, we have always the same issue.

We use the french `fr.js` file : https://blog.lesieur.name/espace-membres/

More details here with another bug : https://github.com/snipcart/snipcart-localization/issues/54

**Comment by JeanSebTr** [comment]
Thanks for the report.

A recent change in the handling of default email templates introduced the bug, it has been fixed.

**Comment by MachinisteWeb** [comment]
Tested and all is good now. Thx.
